export const ALL_TESTIMONIALS_API_LOADING = "ALL_TESTIMONIALS_API_LOADING"
export const ALL_TESTIMONIALS_API_SUCCESS = "ALL_TESTIMONIALS_API_SUCCESS"
export const ALL_TESTIMONIALS_ERROR = "ALL_TESTIMONIALS_ERROR"

export const ALL_POST_API_LOADING = "ALL_POST_API_LOADING"
export const ALL_POST_API_SUCCESS = "ALL_POST_API_SUCCESS"
export const ALL_POST_ERROR = "ALL_POST_ERROR"


export const ALL_ADVERTISEMENT_API_LOADING = "ALL_ADVERTISEMENT_API_LOADING"
export const ALL_ADVERTISEMENT_API_SUCCESS = "ALL_ADVERTISEMENT_API_SUCCESS"
export const ALL_ADVERTISEMENT_ERROR = "ALL_ADVERTISEMENT_ERROR"


export const ALL_OFFER_API_LOADING = "ALL_OFFER_API_LOADING"
export const ALL_OFFER_API_SUCCESS = "ALL_OFFER_API_SUCCESS"
export const ALL_OFFER_ERROR = "ALL_OFFER_ERROR"