export const SERVICE_PROVIDER_SIGNUP_API_LOADING = "SERVICE_PROVIDER_SIGNUP_API_LOADING";
export const SERVICE_PROVIDER_SIGNUP_API_SUCCESS = "SERVICE_PROVIDER_SIGNUP_API_SUCCESS";
export const SERVICE_PROVIDER_SIGNUP_API_ERROR = "SERVICE_PROVIDER_SIGNUP_API_ERROR";

export const SERVICE_PROVIDER_LOGIN_API_LOADING = "SERVICE_PROVIDER_LOGIN_API_LOADING";
export const SERVICE_PROVIDER_LOGIN_API_SUCCESS = "SERVICE_PROVIDER_LOGIN_API_SUCCESS";
export const SERVICE_PROVIDER_LOGIN_API_ERROR = "SERVICE_PROVIDER_LOGIN_API_ERROR";



// get All service provder data 
export const SERVICE_PROVIDER_ALL_API_LOADING = "SERVICE_PROVIDER_ALL_API_LOADING";
export const SERVICE_PROVIDER_ALL_API_SUCCESS = "SERVICE_PROVIDER_ALL_API_SUCCESS";
export const SERVICE_PROVIDER_ALL_API_ERROR = "SERVICE_PROVIDER_ALL_API_ERROR";