

// Add Head Expense constants
export const HEAD_EXPENSE_API_LOADING = "HEAD_EXPENSE_API_LOADING"
export const HEAD_EXPENSE_API_ERROR = "HEAD_EXPENSE_API_ERROR"
export const HEAD_EXPENSE_API_SUCCESS = "HEAD_EXPENSE_API_SUCCESS"



// Get all the Head Expenses 
export const GET_ALLHEADEXP_API_LOADING = "GET_ALLHEADEXP_API_LOADING";
export const GET_ALLHEADEXP_API_ERROR = "GET_ALLHEADEXP_API_ERROR";
export const GET_ALLHEADEXP_API_SUCCESS = "GET_ALLHEADEXP_API_SUCCESS";


// delet head expense by id
export const GET_DEL_HEADEXP_LOADING = 'GET_DEL_HEADEXP_LOADING';
export const GET_DEL_HEADEXP_SUCCESS = 'GET_DEL_HEADEXP_SUCCESS';
export const GET_DEL_HEADEXP_ERROR = 'GET_DEL_HEADEXP_ERROR';



// get add the expenses 

export const GET_ADDEXP_API_LOADING = 'GET_ADDEXP_API_LOADING';
export const GET_ADDEXP_API_SUCCESS = 'GET_ADDEXP_API_SUCCESS';
export const GET_ADDEXP_API_ERROR = 'GET_ADDEXP_API_ERROR';


// get add the collections
export const GET_ADD_COLLECTION_LOADING = 'GET_ADD_COLLECTION_LOADING';
export const GET_ADD_COLLECTION_ERROR = 'GET_ADD_COLLECTION_ERROR';
export const GET_ADD_COLLECTION_SUCCESS = 'GET_ADD_COLLECTION_SUCCESS';



// get all expenses 

export const GET_ALL_EXP_API_LOADING = 'GET_ALL_EXP_API_LOADING';
export const GET_ALL_EXP_API_SUCCESS = 'GET_ALL_EXP_API_SUCCESS';
export const GET_ALL_EXP_API_ERROR = 'GET_ALL_EXP_API_ERROR';



// get all the collections
export const GET_ALL_COLL_API_LOADING = 'GET_ALL_COLL_API_LOADING';
export const GET_ALL_COLL_API_SUCCESS = 'GET_ALL_COLL_API_SUCCESS';
export const GET_ALL_COLL_API_ERROR = 'GET_ALL_COLL_API_ERROR';
