export const INVENTRY_API_LOADING = "INVENTRY_API_LOADING"
export const INVENTRY_API_ERROR = "INVENTRY_API_ERROR"
export const INVENTRY_API_SUCCESS = "INVENTRY_API_SUCCESS"


export const ALLOTEDITEM_API_LOADING = "ALLOTEDITEM_API_LOADING"
export const ALLOTEDITEM_API_ERROR = "ALLOTEDITEM_API_ERROR"
export const ALLOTEDITEM_API_SUCCESS = "ALLOTEDITEM_API_SUCCESS"

